<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles generated by SASS-->
    <link rel="stylesheet" href="{{ asset('css/frontend.css') }}">

    <link rel="icon" href="{{asset('favicon100x100.jpg')}}" sizes="32x32">
    <link rel="icon" href="{{asset('favicon300x300.jpg')}}" sizes="192x192">


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="{{ asset('css/frontend/plugins/font-awesome.min.css') }}" rel="stylesheet">

</head>

<body class="{{isset($withImageHeader) && $withImageHeader ? 'with-image-header' : ''}}">
    @include('layouts.frontend.header')
    <div id="app">
        @yield('content')
    </div>
    @include('layouts.frontend.footer')
    
    <script src="{{ asset('js/app.js') }}"></script>
    <!-- jquery -->
    <script src="{{asset('js/frontend/plugins/jquery-1.12.1.min.js')}}"></script>
    <!-- popper js -->
    <script src="{{asset('js/frontend/plugins/popper.min.js')}}"></script>
    <!-- bootstrap js -->
    <script src="{{asset('js/frontend/plugins/bootstrap.min.js')}}"></script>
    <!-- easing js -->
    <script src="{{asset('js/frontend/plugins/jquery.magnific-popup.js')}}"></script>
    <!-- swiper js -->
    <script src="{{asset('js/frontend/plugins/swiper.min.js')}}"></script>
    <!-- swiper js -->
    <script src="{{asset('js/frontend/plugins/masonry.pkgd.js')}}"></script>
    <!-- particles js -->
    <script src="{{asset('js/frontend/plugins/owl.carousel.min.js')}}"></script>
    <!-- swiper js -->
    <script src="{{asset('js/frontend/plugins/slick.min.js')}}"></script>
    <script src="{{asset('js/frontend/plugins/jquery.counterup.min.js')}}"></script>
    <script src="{{asset('js/frontend/plugins/waypoints.min.js')}}"></script>
    <!-- custom js -->
    <script src="{{asset('js/frontend/plugins/custom.min.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    

    @yield('scripts')
</body>

</html>